### ISSUE TITLE
[Anon] Bug report: OverlordBtB - German - Infantry Division.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlegroup#13]
**File:** OverlordBtB - German - Infantry Division.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Ost infantry platoon consists of 3 8-men rifle squads and 1 3-men mmg squad, not 3 3-men mmg squads.

**Comment by Multitallented** [comment]
Fixed
