### ISSUE TITLE
[Anon] Bug report: OverlordBtB - British Commonwealth.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlegroup#4]
**File:** OverlordBtB - British Commonwealth.catz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** Great to see Battlegroup data but...
If I create a simple British Armoured force for FotR of FWD HQ, Inf Platoon and a Sherman Tank Troop everything looks (very) good. I can create a similar force for BtB, namely Armoured Div with FWD HQ, Inf Platoon and  Sherman Tank Troop, however when I do this the details for the Sherman and Firefly weapons (main and small arms) do not appear and only armour type and movement is listed. 
I've tried to look at the xml files as I suspect there is an typo in the BtB one but my programming skills tend to stop at FORTRAN and BASIC

**Comment by Multitallented** [comment]
I've fixed this now. Look for it in the next update

**Comment by Hebason** [comment]
Thankyou. I have created an account for Github now as I have noticed a few other issues with some of the data entries. I will try to get them in order and post them as bug reports soon(ish) and will get the latest data sets for Battlescribe
